import './globals.css'
import Navigator from '../components/Navigator';

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create Samess',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className="w-full max-w-[575px] m-auto text-black bg-white dark:text-white dark:bg-[#1c1c1c] transition-colors duration-300">
          <Navigator>
            {children}
          </Navigator>
      </body>
    </html>
  )
}
